name: qr_earth_admin
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.1
  cupertino_icons: ^1.0.8
  go_router: ^14.3.0
  http: ^1.2.2
  infinite_scroll_pagination: ^4.0.0
  loader_overlay: ^4.0.3
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.2
  pdf: ^3.11.1
  printing: ^5.13.4
  file_picker: ^8.1.3
  bitsdojo_window: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
